# Generated by Django 3.0.7 on 2020-09-12 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0047_auto_20200912_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=254)),
                ('disc_topic_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion', to='profiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('disc_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Discussion')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to='profiles.UserProfile')),
            ],
        ),
    ]
