# Generated by Django 3.0.7 on 2020-09-12 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0047_auto_20200912_1209'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=254)),
                ('disc_topic_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='profiles.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Discussions',
            },
        ),
        migrations.AlterField(
            model_name='discussion_comments',
            name='disc_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.Discussions'),
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
