# Generated by Django 3.0.7 on 2020-09-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200912_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussions',
            name='image',
        ),
    ]
