# Generated by Django 3.0.7 on 2020-09-12 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200912_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion_comments',
            options={'verbose_name_plural': 'Discussion Comments'},
        ),
        migrations.AlterField(
            model_name='discussion_comments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='discussion_comments',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
