# Generated by Django 3.0.7 on 2020-08-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200809_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_ssize',
            new_name='product_size',
        ),
    ]
