# Generated by Django 3.0.7 on 2020-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200810_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='non_delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_delivery',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
