# Generated by Django 3.0.7 on 2020-08-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200813_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lineitem_delivery',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='delivery_charge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
