# Generated by Django 3.0.7 on 2020-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200816_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
