# Generated by Django 3.0.7 on 2020-08-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_orderlineitem_delivery_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='delivery_cost',
            new_name='lineitem_deliverycost',
        ),
    ]
