# Generated by Django 3.0.7 on 2020-08-18 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200817_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(default=104, on_delete=django.db.models.deletion.CASCADE, to='checkout.Country'),
        ),
    ]
