# Generated by Django 3.0.7 on 2020-08-18 22:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20200818_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
