# Generated by Django 3.0.7 on 2020-07-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200725_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subscription_type',
        ),
    ]
