# Generated by Django 3.0.7 on 2020-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='products.Sizes'),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_type',
            field=models.ManyToManyField(to='products.Subscription_Type'),
        ),
    ]
