# Generated by Django 3.0.7 on 2020-08-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200803_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_subscription',
            name='product',
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('product_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product_Subscription')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_sub',
            field=models.ManyToManyField(through='products.Subscriptions', to='products.Product_Subscription'),
        ),
    ]
