# Generated by Django 3.0.7 on 2020-08-04 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200804_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 4, 12, 15, 0, 686981, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 8, 4, 12, 13, 43, 105819, tzinfo=utc), max_length=254, null=True),
        ),
    ]
