# Generated by Django 3.0.7 on 2020-08-06 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200804_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(blank=True, default=datetime.datetime(2020, 8, 6, 15, 36, 27, 186853, tzinfo=utc), max_length=254, null=True),
        ),
    ]
