# Generated by Django 3.0.7 on 2020-08-13 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200813_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_charge',
        ),
        migrations.AddField(
            model_name='product_subscription',
            name='delivery_charge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 13, 19, 38, 37, 96713, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 13, 19, 38, 37, 98652, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
