# Generated by Django 3.0.7 on 2020-08-13 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20200813_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 13, 20, 58, 5, 974955, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 13, 20, 58, 5, 976377, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
