# Generated by Django 3.0.7 on 2020-08-17 13:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200817_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 17, 13, 44, 47, 165529, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 17, 13, 44, 47, 167515, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
