# Generated by Django 3.0.7 on 2020-08-18 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200817_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 18, 0, 31, 27, 644115, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 18, 0, 31, 27, 645259, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
