# Generated by Django 3.0.7 on 2020-08-18 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200818_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 18, 22, 37, 1, 747081, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 18, 22, 37, 1, 748416, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
