# Generated by Django 3.0.7 on 2020-08-22 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200822_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 22, 18, 39, 52, 354707, tzinfo=utc), max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=datetime.datetime(2020, 8, 22, 18, 39, 52, 355882, tzinfo=utc), max_length=20, unique=True),
        ),
    ]
