# Generated by Django 3.0.7 on 2020-08-29 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20200822_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
