# Generated by Django 3.0.7 on 2020-08-29 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_auto_20200829_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product_subscription',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
