# Generated by Django 3.0.7 on 2020-08-29 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200829_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_subscription',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
