# Generated by Django 3.0.7 on 2020-08-31 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_product_subscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
    ]
