# Generated by Django 3.0.7 on 2020-09-05 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('products', '0036_auto_20200831_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('full_name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='profiles.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
