# Generated by Django 3.0.7 on 2020-09-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200906_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
