# Generated by Django 3.0.7 on 2020-09-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_remove_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
