# Generated by Django 3.0.7 on 2020-09-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20200908_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
