# Generated by Django 3.0.7 on 2020-09-10 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
